name: Copy AGENTS to CLAUDE

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  copy-agents:
    # Run on: direct pushes to main, open/updated PRs, or merged PRs
    if: github.event_name == 'push' || github.event.pull_request.merged == true || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # For merged PRs: checkout the merge commit (prioritize over head)
          # For open PRs: checkout the PR branch
          # For direct pushes: checkout the pushed commit
          ref: ${{ github.event.pull_request.merged == true && github.event.pull_request.merge_commit_sha || github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Copy AGENTS.md to CLAUDE.md
        run: cp AGENTS.md CLAUDE.md

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CLAUDE.md

          # Determine target branch
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
              # For merged PRs: push to base branch (main)
              TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
            else
              # For open PRs: push to PR branch
              TARGET_BRANCH="${{ github.event.pull_request.head.ref }}"
            fi
          else
            # For direct pushes: push to the same branch
            TARGET_BRANCH="${{ github.ref_name }}"
          fi

          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to CLAUDE.md"
          else
            git commit -m "chore: Sync CLAUDE.md with AGENTS.md [skip ci]"
            git push origin HEAD:$TARGET_BRANCH
          fi
