name: Update Doc Frontmatter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  update-frontmatter:
    # Run on: direct pushes to main, open/updated PRs, or merged PRs
    if: github.event_name == 'push' || github.event.pull_request.merged == true || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # For merged PRs: checkout the merge commit (prioritize over head)
          # For open PRs: checkout the PR branch
          # For direct pushes: checkout the pushed commit
          ref: ${{ github.event.pull_request.merged == true && github.event.pull_request.merge_commit_sha || github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update doc frontmatter
        run: |
          # Make script executable
          chmod +x scripts/update_doc_frontmatter.py

          # Run the script to update frontmatter of modified markdown files
          python scripts/update_doc_frontmatter.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage any modified markdown files
          git add '*.md' || true

          # Determine target branch
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
              # For merged PRs: push to base branch (main)
              TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
            else
              # For open PRs: push to PR branch
              TARGET_BRANCH="${{ github.event.pull_request.head.ref }}"
            fi
          else
            # For direct pushes: push to the same branch
            TARGET_BRANCH="${{ github.ref_name }}"
          fi

          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to documentation frontmatter"
          else
            git commit -m "chore: Update doc frontmatter [skip ci]"
            git push origin HEAD:$TARGET_BRANCH
          fi
